# Generated by Django 3.0.3 on 2020-06-29 12:09

from django.db import migrations,models



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
