# Generated by Django 3.0.3 on 2020-07-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
                ('from_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
    ]
