# Generated by Django 3.0.3 on 2020-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msf_id',
            new_name='msg_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='from_email',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
